name: 'Slack Notifier'
description: 'Post to Slack'
inputs:
  slack-webHook:
    description: 'slack webhook'
    required: true
  slack-channel:
    description: 'slack channel'
    required: false
  job-status:
    description: 'job status'
    required: false
  plan-status:
    description: 'plan status'
    required: false
  slack-text:
    description: 'text'
    required: true
  parameters:
    description: 'parameters'
    required: false
  created-by:
    description: 'created by'
    required: false
  slack-username:
    description: 'username'
    required: false
  slack-icon:
    description: 'icon'
    required: false
  slack-icon-emoji:
    description: 'icon emoji'
    required: false
  is-basic:
    required: false
outputs:
  result:
    description: 'result'
runs:
  using: 'node12'
  main: 'dist/index.js'
